#!/bin/bash

# system preferences
export TERM="xterm-256color"
export LANG=en_US.UTF-8
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Prefered programs
export EDITOR='vim'
if type most > /dev/null; then
    export PAGER='most'
else
    export PAGER='less'
fi


# Change Path
export PATH="${PATH}:$HOME/.local/bin"
export PATH="${PATH}:$HOME/bin"
export PATH="${PATH}:$HOME/.cargo/bin"

